In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
import math 
import random as rn
import matplotlib.pyplot as plt

In [54]:
def split(x, k):  
    splitPoint = int(len(x) * k)
    return x.iloc[:splitPoint], x.iloc[splitPoint:]

def getDistances(x, sample, columnNames, function, power):
    lis = []
    for i in range(len(x)):
        y=0
        for column in columnNames:
            y+=(function(x.loc[i,column], sample[column], power))
        lis.append(y)
    return lis


def manhattan(first, second, n):
    return abs(first - second)
        

def euclides(first, second, n):
    difference = math.pow(first, n) - math.pow(second, n)
    return difference ** 1/n

def sort(x, lis):
        x['distance'] = lis
        return x.sort_values(by=['distance'])

def shuffle(x):
    for i in range(len(x) - 1, 0, -1):
        j = rn.randint(0, i - 1)
        x.iloc[i], x.iloc[j] = x.iloc[j], x.iloc[i]

def knn(recs,k):
    dict={1:0,0:0}
    knn=recs.iloc[:k]['RainTomorrow']
    for i in knn:
        if i:
            dict[1]+=1
        else:
            dict[0]+=1
    return (max(dict, key=dict.get))

def knnRain(recs,k):
    
    
    rain=recs.iloc[:k]['Rainfall']
    mean = rain.mean()
    sigm = rain.std()
  
    return mean,sigm

def knnTemp(recs,k):  
    rain=recs.iloc[:k]['AvgTemp']
    mean = rain.mean()
    sigm = rain.std()
  
    return mean,sigm

def avgTemp(x):
    lis = []
    for i in range(len(x)):
        lis.append(x.iloc[i]['Temp3pm']+x.iloc[i]['Temp9am']*0.5)
    x['AvgTemp'] = lis

In [55]:
data = pd.read_csv('WeatherTrainingData.csv')
data.drop(labels=['Location','Evaporation', 'WindDir9am', 'WindDir3pm' ,'WindGustDir','Sunshine' ], inplace=True, axis=1)
data["Cloud3pm"].fillna(0, inplace = True)
data["Cloud9am"].fillna(0, inplace = True)
data.replace({'RainToday': {"No": 0, 'Yes': 1}},inplace=True)
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)
data

,row ID,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Row0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,0.0,16.9,21.8,0.0,0
1,Row1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,0.0,0.0,17.2,24.3,0.0,0
2,Row2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0.0,0
3,Row3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,0.0,0.0,20.6,28.9,0.0,0
4,Row4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,0.0,0.0,16.3,25.5,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83804,Row101816,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,1024.3,0.0,7.0,11.6,20.0,0.0,0
83805,Row101817,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,0.0,0.0,9.4,20.9,0.0,0
83806,Row101818,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,0.0,0.0,10.1,22.4,0.0,0
83807,Row101819,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,0.0,0.0,10.9,24.5,0.0,0
83808,Row101820,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,0.0,0.0,12.5,26.1,0.0,0

In [56]:
#data.drop(labels=['row ID' ,'WindGustSpeed',	'WindSpeed9am'	,'WindSpeed3pm',	'Humidity9am',	'Humidity3pm',	'Pressure9am',	'Pressure3pm',	'Cloud9am',	'Cloud3pm',	'Temp9am'	,'Temp3pm'	,'RainToday',	'RainTomorrow'], inplace=True, axis=1)
"""
#data=data["Temp3pm"]
data2=data[:400]
#for i in range (len(data2)):
 #   data2.iloc[i]['AvgTemp']=data2.iloc[i]['Temp3pm']+data2.iloc[i]['Temp9am']*0.5

lis = []
for i in range(len(data2)):
    lis.append(data2.iloc[i]['Temp3pm']+data2.iloc[i]['Temp9am']*0.5)
data2['AvgTemp'] = lis
sns.relplot(data=data2, x="row ID", y="AvgTemp", hue="RainToday")
plt.show()

"""

'\n#data=data["Temp3pm"]\ndata2=data[:400]\n#for i in range (len(data2)):\n #   data2.iloc[i][\'AvgTemp\']=data2.iloc[i][\'Temp3pm\']+data2.iloc[i][\'Temp9am\']*0.5\n\nlis = []\nfor i in range(len(data2)):\n    lis.append(data2.iloc[i][\'Temp3pm\']+data2.iloc[i][\'Temp9am\']*0.5)\ndata2[\'AvgTemp\'] = lis\nsns.relplot(data=data2, x="row ID", y="AvgTemp", hue="RainToday")\nplt.show()\n\n'

In [57]:

values=data.select_dtypes(exclude="object")
columnNames=values.columns.tolist()
columnNames=columnNames[:-2]
#doDeszczuIlosc
#columnNames=['MinTemp',	'MaxTemp','WindGustSpeed',	'WindSpeed9am',	'WindSpeed3pm',	'Humidity9am',	'Humidity3pm',	'Pressure9am',	'Pressure3pm',	'Cloud9am',	'Cloud3pm',	'Temp9am',	'Temp3pm']
#doTemp
columnNames=['MinTemp',	'Rainfall','MaxTemp','WindGustSpeed',	'WindSpeed9am',	'WindSpeed3pm',	'Humidity9am',	'Humidity3pm',	'Pressure9am',	'Pressure3pm',	'Cloud9am',	'Cloud3pm']

for column in columnNames:
        x=data.loc[:,column]
        min1=min(x)
        max1=max(x)
        for row in range (len(data)):
            xprim=(data.at[row,column]-min1)/(max1-min1)
            data.at[row,column]=xprim

In [58]:
data = data.sample(frac=1).reset_index(drop=True)#tasowanie
ts,vs=split(data,0.7)
data

,row ID,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Row60645,0.420538,0.448352,0.000000,0.108527,0.045977,0.068966,0.56,0.24,0.629752,0.623779,0.000000,0.000000,16.9,22.6,0.0,0
1,Row9440,0.838631,0.876923,0.000000,0.627907,0.379310,0.218391,0.54,0.26,0.500826,0.470684,0.222222,0.333333,30.0,40.2,0.0,1
2,Row43465,0.083130,0.215385,0.000000,0.108527,0.068966,0.080460,0.91,0.45,0.846281,0.786645,0.444444,0.444444,0.2,12.1,0.0,0
3,Row49722,0.271394,0.259341,0.000000,0.124031,0.103448,0.103448,0.99,0.55,0.869421,0.855049,0.777778,0.666667,6.7,14.1,0.0,0
4,Row53460,0.366748,0.274725,0.008161,0.124031,0.080460,0.149425,0.95,0.79,0.871074,0.861564,0.888889,0.666667,11.6,14.3,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83804,Row83451,0.356968,0.400000,0.000000,0.240310,0.172414,0.252874,0.73,0.45,0.838017,0.781759,0.222222,0.555556,14.8,19.8,0.0,0
83805,Row19569,0.493888,0.604396,0.000000,0.186047,0.000000,0.103448,0.79,0.31,0.659504,0.607492,0.000000,0.000000,18.2,27.8,0.0,0
83806,Row53564,0.513447,0.402198,0.000000,0.186047,0.172414,0.195402,0.67,0.58,0.568595,0.571661,0.111111,0.000000,17.4,19.7,0.0,0
83807,Row54518,0.388753,0.281319,0.008705,0.542636,0.321839,0.528736,0.80,0.77,0.504132,0.547231,0.888889,0.888889,11.6,14.2,1.0,0
83808,Row99374,0.797066,0.672527,0.008161,0.186047,0.172414,0.195402,0.82,0.55,0.509091,0.482085,0.222222,0.666667,29.4,32.4,1.0,0

In [59]:
ts=ts[:100]
vs=vs[:10]

In [60]:
values=data.select_dtypes(exclude="object")
columnNames=values.columns.tolist()

In [61]:
counter = 0
for i, r in vs.iterrows():
    lis = getDistances(ts, r, columnNames, euclides, 3)
    recs = sort(ts, lis)
    if knn(recs,10)==r['RainTomorrow']:
        counter+=1
print( counter / len(vs))

0.9

In [80]:
counter = 0
for i, r in vs.iterrows():
    lis = getDistances(ts, r, columnNames, euclides, 3)
    recs = sort(ts, lis)
    d,o=knnRain(recs,10)
    
    #if d==r['Rainfall']:
    if (d-o)<=r['Rainfall'] and (d+o)>=r['Rainfall']:
        counter+=1
print( counter / len(vs))

0.8

In [79]:
counter = 0
avgTemp(ts)
avgTemp(vs)

for i, r in vs.iterrows():
    lis = getDistances(ts, r, columnNames, euclides, 2)
    recs = sort(ts, lis)
    d,o=knnTemp(recs,10)
    if (d-o)<=r['AvgTemp'] and (d+o)>=r['AvgTemp']:
    
        counter+=1
print( counter / len(vs))

0.2

In [64]:
data=data[:40]
sns.relplot(data=data, x="row ID", y="AvgTemp", hue="RainToday")
plt.show()

ValueError: Could not interpret value `AvgTemp` for parameter `y`