In [88]:
import pandas as pd
import numpy as np
import seaborn as sns
import math 
import random as rn
import matplotlib.pyplot as plt

In [89]:
data = pd.read_csv('WeatherTrainingData.csv')
data.drop(labels=['Location','Evaporation', 'WindDir9am', 'WindDir3pm' ,'WindGustDir','Sunshine','row ID', 'RainTomorrow' ], inplace=True, axis=1)
data["Cloud3pm"].fillna(0, inplace = True)
data["Cloud9am"].fillna(0, inplace = True)
data.replace({'RainToday': {"No": 0, 'Yes': 1}},inplace=True)
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)
data = data[:len(data)//2]
data

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,0.0,16.9,21.8,0.0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,0.0,0.0,17.2,24.3,0.0
2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0.0
3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,0.0,0.0,20.6,28.9,0.0
4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,0.0,0.0,16.3,25.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41899,5.4,13.4,2.0,59.0,24.0,31.0,84.0,75.0,1011.6,1009.4,0.0,0.0,8.2,11.9,1.0
41900,2.1,13.2,2.4,30.0,15.0,15.0,95.0,62.0,1021.0,1021.0,0.0,0.0,4.5,12.4,1.0
41901,4.4,16.5,0.0,48.0,15.0,31.0,92.0,53.0,1021.0,1016.9,0.0,0.0,8.2,16.0,0.0
41902,6.1,14.5,0.4,44.0,11.0,28.0,98.0,68.0,1023.3,1022.5,0.0,0.0,6.9,13.7,0.0
41903,6.1,16.2,0.0,30.0,11.0,19.0,97.0,58.0,1028.9,1027.6,0.0,0.0,8.8,15.6,0.0

In [90]:
avgtemp = [0]*len(data)
avgwind = [0]*len(data)
avghumidity = [0]*len(data)
avgpressure = [0]*len(data)
avgclouds = [0]*len(data)

len(avgtemp)
for i in range (len(data)):
    avgtemp[i] = (data.iloc[i]['Temp3pm']+data.iloc[i]['Temp9am'])*0.5
    avgwind[i] = (data.iloc[i]['WindSpeed9am']+data.iloc[i]['WindSpeed3pm'])*0.5
    avghumidity[i]=(data.iloc[i]['Humidity9am']+data.iloc[i]['Humidity3pm'])*0.5
    avgpressure[i]=(data.iloc[i]['Pressure9am']+data.iloc[i]['Pressure3pm'])*0.5
    avgclouds[i]=(data.iloc[i]['Cloud9am']+data.iloc[i]['Cloud3pm'])*0.5
data['AvgTemp'] = avgtemp
data['AvgWind'] = avgwind
data['AvgHumidity'] = avghumidity
data['AvgPressure'] = avgpressure
data['AvgClouds'] = avgclouds
data.drop(labels=['Temp3pm','Temp9am','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
                   'Humidity3pm',  'Pressure9am',  'Pressure3pm', 'Cloud9am', 'Cloud3pm'], inplace=True, axis=1)
data

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,RainToday,AvgTemp,AvgWind,AvgHumidity,AvgPressure,AvgClouds
0,13.4,22.9,0.6,44.0,0.0,19.35,22.0,46.5,1007.40,4.0
1,7.4,25.1,0.0,44.0,0.0,20.75,13.0,34.5,1009.20,0.0
2,17.5,32.3,1.0,41.0,0.0,23.75,13.5,57.5,1008.40,7.5
3,14.6,29.7,0.2,56.0,0.0,24.75,21.5,39.0,1007.30,0.0
4,7.7,26.7,0.0,35.0,0.0,20.90,11.5,33.5,1011.75,0.0
...,...,...,...,...,...,...,...,...,...,...
41899,5.4,13.4,2.0,59.0,1.0,10.05,27.5,79.5,1010.50,0.0
41900,2.1,13.2,2.4,30.0,1.0,8.45,15.0,78.5,1021.00,0.0
41901,4.4,16.5,0.0,48.0,0.0,12.10,23.0,72.5,1018.95,0.0
41902,6.1,14.5,0.4,44.0,0.0,10.30,19.5,83.0,1022.90,0.0
41903,6.1,16.2,0.0,30.0,0.0,12.20,15.0,77.5,1028.25,0.0

In [91]:
cols_to_norm = ['MinTemp', 'MaxTemp', 'WindGustSpeed', 'AvgTemp', 'AvgWind', 'AvgHumidity', 'AvgPressure', 'AvgClouds']
data[cols_to_norm] = data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
data

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,RainToday,AvgTemp,AvgWind,AvgHumidity,AvgPressure,AvgClouds
0,0.524422,0.454139,0.6,0.289062,0.0,0.45250,0.273292,0.442708,0.465488,0.5000
1,0.370180,0.503356,0.0,0.289062,0.0,0.48750,0.161491,0.317708,0.495791,0.0000
2,0.629820,0.664430,1.0,0.265625,0.0,0.56250,0.167702,0.557292,0.482323,0.9375
3,0.555270,0.606264,0.2,0.382812,0.0,0.58750,0.267081,0.364583,0.463805,0.0000
4,0.377892,0.539150,0.0,0.218750,0.0,0.49125,0.142857,0.307292,0.538721,0.0000
...,...,...,...,...,...,...,...,...,...,...
41899,0.318766,0.241611,2.0,0.406250,1.0,0.22000,0.341615,0.786458,0.517677,0.0000
41900,0.233933,0.237136,2.4,0.179688,1.0,0.18000,0.186335,0.776042,0.694444,0.0000
41901,0.293059,0.310962,0.0,0.320312,0.0,0.27125,0.285714,0.713542,0.659933,0.0000
41902,0.336761,0.266219,0.4,0.289062,0.0,0.22625,0.242236,0.822917,0.726431,0.0000
41903,0.336761,0.304251,0.0,0.179688,0.0,0.27375,0.186335,0.765625,0.816498,0.0000

In [ ]:
data.to_csv('Normalized_data.csv')